config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :voting_blocks
  resources :baby_names
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby_name.rb
class BabyName < ApplicationRecord
end

app/models/vote.rb
class Vote < ApplicationRecord
  has_one :voting_block
  has_one :baby_name
end

app/models/voting_block.rb
class VotingBlock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/baby_names_controller.rb
class BabyNamesController < ApplicationController
  before_action :set_baby_name, only: [:show, :edit, :update, :destroy]

  # GET /baby_names
  # GET /baby_names.json
  def index
    @baby_names = BabyName.all
  end

  # GET /baby_names/1
  # GET /baby_names/1.json
  def show
  end

  # GET /baby_names/new
  def new
    @baby_name = BabyName.new
  end

  # GET /baby_names/1/edit
  def edit
  end

  # POST /baby_names
  # POST /baby_names.json
  def create
    @baby_name = BabyName.new(baby_name_params)

    respond_to do |format|
      if @baby_name.save
        format.html { redirect_to @baby_name, notice: 'Baby name was successfully created.' }
        format.json { render :show, status: :created, location: @baby_name }
      else
        format.html { render :new }
        format.json { render json: @baby_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baby_names/1
  # PATCH/PUT /baby_names/1.json
  def update
    respond_to do |format|
      if @baby_name.update(baby_name_params)
        format.html { redirect_to @baby_name, notice: 'Baby name was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby_name }
      else
        format.html { render :edit }
        format.json { render json: @baby_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baby_names/1
  # DELETE /baby_names/1.json
  def destroy
    @baby_name.destroy
    respond_to do |format|
      format.html { redirect_to baby_names_url, notice: 'Baby name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby_name
      @baby_name = BabyName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_name_params
      params.require(:baby_name).permit(:name, :boy, :girl)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:vote, :voting_block_id, :baby_name_id)
    end
end

app/controllers/voting_blocks_controller.rb
class VotingBlocksController < ApplicationController
  before_action :set_voting_block, only: [:show, :edit, :update, :destroy]

  # GET /voting_blocks
  # GET /voting_blocks.json
  def index
    @voting_blocks = VotingBlock.all
  end

  # GET /voting_blocks/1
  # GET /voting_blocks/1.json
  def show
  end

  # GET /voting_blocks/new
  def new
    @voting_block = VotingBlock.new
  end

  # GET /voting_blocks/1/edit
  def edit
  end

  # POST /voting_blocks
  # POST /voting_blocks.json
  def create
    @voting_block = VotingBlock.new(voting_block_params)

    respond_to do |format|
      if @voting_block.save
        format.html { redirect_to @voting_block, notice: 'Voting block was successfully created.' }
        format.json { render :show, status: :created, location: @voting_block }
      else
        format.html { render :new }
        format.json { render json: @voting_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voting_blocks/1
  # PATCH/PUT /voting_blocks/1.json
  def update
    respond_to do |format|
      if @voting_block.update(voting_block_params)
        format.html { redirect_to @voting_block, notice: 'Voting block was successfully updated.' }
        format.json { render :show, status: :ok, location: @voting_block }
      else
        format.html { render :edit }
        format.json { render json: @voting_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voting_blocks/1
  # DELETE /voting_blocks/1.json
  def destroy
    @voting_block.destroy
    respond_to do |format|
      format.html { redirect_to voting_blocks_url, notice: 'Voting block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voting_block
      @voting_block = VotingBlock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voting_block_params
      params.require(:voting_block).permit(:random)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baby_names_helper.rb
module BabyNamesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/voting_blocks_helper.rb
module VotingBlocksHelper
end

app/views/baby_names/_form.html.erb
<%= form_with(model: baby_name, local: true) do |form| %>
  <% if baby_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby_name.errors.count, "error") %> prohibited this baby_name from being saved:</h2>

      <ul>
      <% baby_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :baby_name_name %>
  </div>

  <div class="field">
    <%= form.label :boy %>
    <%= form.text_field :boy, id: :baby_name_boy %>
  </div>

  <div class="field">
    <%= form.label :girl %>
    <%= form.text_field :girl, id: :baby_name_girl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/baby_names/edit.html.erb
<h1>Editing Baby Name</h1>

<%= render 'form', baby_name: @baby_name %>

<%= link_to 'Show', @baby_name %> |
<%= link_to 'Back', baby_names_path %>

app/views/baby_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baby Names</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Boy</th>
      <th>Girl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baby_names.each do |baby_name| %>
      <tr>
        <td><%= baby_name.name %></td>
        <td><%= baby_name.boy %></td>
        <td><%= baby_name.girl %></td>
        <td><%= link_to 'Show', baby_name %></td>
        <td><%= link_to 'Edit', edit_baby_name_path(baby_name) %></td>
        <td><%= link_to 'Destroy', baby_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby Name', new_baby_name_path %>

app/views/baby_names/new.html.erb
<h1>New Baby Name</h1>

<%= render 'form', baby_name: @baby_name %>

<%= link_to 'Back', baby_names_path %>

app/views/baby_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby_name.name %>
</p>

<p>
  <strong>Boy:</strong>
  <%= @baby_name.boy %>
</p>

<p>
  <strong>Girl:</strong>
  <%= @baby_name.girl %>
</p>

<%= link_to 'Edit', edit_baby_name_path(@baby_name) %> |
<%= link_to 'Back', baby_names_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babyname</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vote %>
    <%= form.text_field :vote, id: :vote_vote %>
  </div>

  <div class="field">
    <%= form.label :voting_block_id %>
    <%= form.text_field :voting_block_id, id: :vote_voting_block_id %>
  </div>

  <div class="field">
    <%= form.label :baby_name_id %>
    <%= form.text_field :baby_name_id, id: :vote_baby_name_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Vote</th>
      <th>Voting block</th>
      <th>Baby name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.vote %></td>
        <td><%= vote.voting_block %></td>
        <td><%= vote.baby_name %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vote:</strong>
  <%= @vote.vote %>
</p>

<p>
  <strong>Voting block:</strong>
  <%= @vote.voting_block %>
</p>

<p>
  <strong>Baby name:</strong>
  <%= @vote.baby_name %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>

app/views/voting_blocks/_form.html.erb
<%= form_with(model: voting_block, local: true) do |form| %>
  <% if voting_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voting_block.errors.count, "error") %> prohibited this voting_block from being saved:</h2>

      <ul>
      <% voting_block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :random %>
    <%= form.text_field :random, id: :voting_block_random %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/voting_blocks/edit.html.erb
<h1>Editing Voting Block</h1>

<%= render 'form', voting_block: @voting_block %>

<%= link_to 'Show', @voting_block %> |
<%= link_to 'Back', voting_blocks_path %>

app/views/voting_blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voting Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Random</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voting_blocks.each do |voting_block| %>
      <tr>
        <td><%= voting_block.random %></td>
        <td><%= link_to 'Show', voting_block %></td>
        <td><%= link_to 'Edit', edit_voting_block_path(voting_block) %></td>
        <td><%= link_to 'Destroy', voting_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voting Block', new_voting_block_path %>

app/views/voting_blocks/new.html.erb
<h1>New Voting Block</h1>

<%= render 'form', voting_block: @voting_block %>

<%= link_to 'Back', voting_blocks_path %>

app/views/voting_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Random:</strong>
  <%= @voting_block.random %>
</p>

<%= link_to 'Edit', edit_voting_block_path(@voting_block) %> |
<%= link_to 'Back', voting_blocks_path %>